version: '3'
services:
  owasp-7-server:
    build:
      context: .
    container_name: owasp-7-server
    ports:
      - "80:80"
    networks:
      - internal
    volumes:
      - ./htdocs:/var/www/html

  owasp-7-stuffing:
    image: openbullet/openbullet2:latest
    container_name: owasp-7-stuffing
    volumes:
      - ./user-data:/app/UserData
    networks:
      - internal
    ports:
      - "8069:5000"

networks:
  internal:
    driver: bridge
